[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[nayatel]
type=aor
contact=sip:10.50.161.248:5060

[nayatel]
type=endpoint
transport=transport-udp
context=from-nayatel
disallow=all
allow=alaw,ulaw
aors=nayatel
direct_media=no

[nayatel]
type=identify
endpoint=nayatel
match=10.50.161.248

[livekit]
type=endpoint
transport=transport-udp
context=default
disallow=all
allow=ulaw,alaw
direct_media=no
ice_support=no
