[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060

[nayatel]
type=aor
contact=sip:10.50.161.248:5060

[nayatel]
type=endpoint
transport=transport-udp
context=from-nayatel
disallow=all
allow=alaw,ulaw
aors=nayatel
direct_media=no

[nayatel]
type=identify
endpoint=nayatel
match=10.50.161.248

[livekit]
type=aor
contact=sip:1vajt4pb62c.sip.livekit.cloud\;transport=tcp

[livekit]
type=endpoint
transport=transport-tcp
context=default
disallow=all
allow=ulaw,alaw
aors=livekit
direct_media=no
ice_support=no
from_domain=1vajt4pb62c.sip.livekit.cloud
