"use client";

import { ShieldCheck, Copy, CheckCircle2, ArrowRight } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

export default function TwoFactorSetupPage() {
    const [copied, setCopied] = useState(false);
    const mockSecret = "JBSWY3DPEHPK3PXP";
    const mockBackupCodes = [
        "8472-9102", "3921-0492", "1829-5830", "5920-1928",
        "0293-4829", "8392-1029", "4820-1928", "9102-3948"
    ];

    const copySecret = () => {
        navigator.clipboard.writeText(mockSecret);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="w-full h-full overflow-y-auto bg-zinc-950 p-8 md:p-10 text-slate-200 flex items-center justify-center">
            <div className="max-w-2xl w-full flex flex-col gap-8">

                <div className="text-center space-y-4">
                    <div className="w-16 h-16 bg-blue-500/10 rounded-full flex items-center justify-center mx-auto border border-blue-500/20">
                        <ShieldCheck className="w-8 h-8 text-blue-500" />
                    </div>
                    <h1 className="text-3xl font-bold text-white">Secure Your Account</h1>
                    <p className="text-zinc-400 max-w-lg mx-auto">
                        Two-factor authentication adds an extra layer of security. You'll need to use an authenticator app (like Google Authenticator or Authy) to scan the QR code below.
                    </p>
                </div>

                <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-8 shadow-2xl space-y-8">

                    <div className="flex flex-col md:flex-row items-center gap-8">
                        {/* Mock QR Code area */}
                        <div className="w-48 h-48 bg-white p-2 rounded-lg flex-shrink-0 flex items-center justify-center">
                            <div className="w-full h-full border-4 border-black border-dashed flex items-center justify-center bg-zinc-100">
                                <span className="text-zinc-400 text-xs font-bold text-center uppercase tracking-wider px-4">
                                    [QR Code Rendered Here]
                                </span>
                            </div>
                        </div>

                        <div className="flex-1 space-y-4 w-full">
                            <div>
                                <h3 className="text-white font-medium mb-1">1. Scan the QR Code</h3>
                                <p className="text-sm text-zinc-400">Open your authenticator app and scan the code. If you can't scan it, enter this secret key manually:</p>
                            </div>

                            <div className="bg-zinc-950 border border-zinc-800 rounded flex items-center p-1">
                                <code className="flex-1 text-center font-mono text-blue-400 tracking-widest">{mockSecret}</code>
                                <button onClick={copySecret} className="p-2 text-zinc-400 hover:text-white transition-colors">
                                    {copied ? <CheckCircle2 className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                                </button>
                            </div>
                        </div>
                    </div>

                    <div className="pt-6 border-t border-zinc-800">
                        <h3 className="text-white font-medium mb-4">2. Enter Verification Code</h3>
                        <p className="text-sm text-zinc-400 mb-4">Enter the 6-digit code generated by your app to verify the setup.</p>

                        <div className="flex gap-4">
                            <input
                                type="text"
                                placeholder="000 000"
                                className="w-full max-w-[200px] bg-zinc-950 border border-zinc-800 rounded-lg px-4 py-3 text-center text-xl tracking-widest text-white font-mono focus:outline-none focus:border-blue-500 placeholder-zinc-700"
                                maxLength={6}
                            />
                            <button className="flex-1 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg px-4 py-3 transition-colors flex items-center justify-center gap-2">
                                Verify & Activate <ArrowRight className="w-4 h-4" />
                            </button>
                        </div>
                    </div>

                </div>

                {/* Backup Codes */}
                <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-6 shadow-xl">
                    <h3 className="text-white font-medium mb-2 text-red-400">Emergency Backup Codes</h3>
                    <p className="text-sm text-zinc-400 mb-6">Store these codes securely. If you lose your device, these codes are the ONLY way to recover your account.</p>

                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                        {mockBackupCodes.map((code, idx) => (
                            <div key={idx} className="bg-zinc-950 border border-zinc-800 rounded px-4 py-2 text-center">
                                <code className="text-zinc-300 font-mono text-sm tracking-wider">{code}</code>
                            </div>
                        ))}
                    </div>

                    <div className="mt-6 flex justify-end">
                        <button className="text-sm text-zinc-400 hover:text-white flex items-center gap-2 transition-colors">
                            <Copy className="w-4 h-4" /> Copy All Codes
                        </button>
                    </div>
                </div>

                <div className="text-center">
                    <Link href="/settings/users" className="text-zinc-500 hover:text-white text-sm transition-colors">
                        ← Back to User Management
                    </Link>
                </div>

            </div>
        </div>
    );
}
