"use client";
import React, { useState } from "react";
import {
    GitBranch, Plus, Trash2, Phone, MessageSquare, Users, Music,
    ChevronRight, Settings, Play, Save, Download, RefreshCw,
    ArrowRight, Voicemail, PhoneForwarded, Hash, CheckCircle2
} from "lucide-react";

type NodeType = "greet" | "menu" | "transfer" | "voicemail" | "queue" | "hangup" | "condition";

interface IVRNode {
    id: string;
    type: NodeType;
    label: string;
    dtmf?: string;
    audioFile?: string;
    target?: string;
    children: string[];
    x: number;
    y: number;
}

const NODE_COLORS: Record<NodeType, { bg: string; border: string; icon: React.ReactNode }> = {
    greet: { bg: "#6366f120", border: "#6366f1", icon: <Play className="w-3.5 h-3.5" /> },
    menu: { bg: "#f59e0b20", border: "#f59e0b", icon: <Hash className="w-3.5 h-3.5" /> },
    transfer: { bg: "#10b98120", border: "#10b981", icon: <PhoneForwarded className="w-3.5 h-3.5" /> },
    voicemail: { bg: "#06b6d420", border: "#06b6d4", icon: <Voicemail className="w-3.5 h-3.5" /> },
    queue: { bg: "#8b5cf620", border: "#8b5cf6", icon: <Users className="w-3.5 h-3.5" /> },
    hangup: { bg: "#ef444420", border: "#ef4444", icon: <Phone className="w-3.5 h-3.5" /> },
    condition: { bg: "#ec489920", border: "#ec4899", icon: <GitBranch className="w-3.5 h-3.5" /> },
};

const INITIAL_NODES: IVRNode[] = [
    { id: "start", type: "greet", label: "Welcome Greeting", audioFile: "welcome.mp3", children: ["menu1"], x: 0, y: 0, dtmf: undefined },
    { id: "menu1", type: "menu", label: "Main Menu", audioFile: "main-menu.mp3", children: ["transfer1", "queue1", "voicemail1"], x: 0, y: 1, dtmf: undefined },
    { id: "transfer1", type: "transfer", label: "Transfer to Sales", dtmf: "1", target: "+61298765432", children: [], x: -2, y: 2, audioFile: undefined },
    { id: "queue1", type: "queue", label: "Support Queue", dtmf: "2", target: "support-queue", children: [], x: 0, y: 2, audioFile: undefined },
    { id: "voicemail1", type: "voicemail", label: "Leave Voicemail", dtmf: "3", target: "inbox-main", children: [], x: 2, y: 2, audioFile: undefined },
];

const GENERATED_DIALPLAN = `; Generated by Voice AI IVR Builder
; ${new Date().toISOString()}

[from-trunk]
exten => _X.,1,NoOp(Incoming call to IVR)
 same => n,Answer()
 same => n,Wait(1)
 same => n,Goto(ivr-main,s,1)

[ivr-main]
exten => s,1,Background(welcome)
 same => n,WaitExten(5)
exten => 1,1,Dial(SIP/sales,20,tT)
exten => 2,1,Queue(support-queue)
exten => 3,1,VoiceMail(1@default,u)
exten => t,1,Hangup()
exten => i,1,Playback(invalid)
 same => n,Goto(ivr-main,s,1)`;

let nodeIdCounter = 10;

export default function IVRPage() {
    const [nodes, setNodes] = useState(INITIAL_NODES);
    const [selected, setSelected] = useState<IVRNode | null>(null);
    const [showDialplan, setShowDialplan] = useState(false);
    const [saved, setSaved] = useState(false);

    const addNode = (type: NodeType) => {
        const newNode: IVRNode = {
            id: `node${++nodeIdCounter}`, type, label: `New ${type}`,
            children: [], x: 0, y: 3, audioFile: undefined, dtmf: undefined, target: undefined
        };
        setNodes(prev => [...prev, newNode]);
        setSelected(newNode);
    };

    const deleteNode = (id: string) => {
        if (id === "start") return;
        setNodes(prev => prev.filter(n => n.id !== id).map(n => ({ ...n, children: n.children.filter(c => c !== id) })));
        if (selected?.id === id) setSelected(null);
    };

    const updateNode = (id: string, updates: Partial<IVRNode>) => {
        setNodes(prev => prev.map(n => n.id === id ? { ...n, ...updates } : n));
        if (selected?.id === id) setSelected(s => s ? { ...s, ...updates } : null);
    };

    const handleSave = () => { setSaved(true); setTimeout(() => setSaved(false), 2000); };

    // Build tree display
    const buildTree = (nodeId: string, depth = 0): React.ReactNode => {
        const node = nodes.find(n => n.id === nodeId);
        if (!node) return null;
        const cfg = NODE_COLORS[node.type];
        return (
            <div key={node.id} className="flex flex-col items-center">
                <div
                    className={`relative border-2 rounded-xl px-4 py-3 min-w-[140px] text-center cursor-pointer transition-all hover:scale-105 ${selected?.id === node.id ? "scale-105 ring-2 ring-white" : ""}`}
                    style={{ background: cfg.bg, borderColor: cfg.border }}
                    onClick={() => setSelected(node)}
                >
                    {node.dtmf && (
                        <div className="absolute -top-2 -left-2 w-5 h-5 bg-amber-500 text-white text-[10px] font-bold rounded-full flex items-center justify-center">
                            {node.dtmf}
                        </div>
                    )}
                    <div className="flex items-center justify-center gap-1.5 mb-1" style={{ color: cfg.border }}>
                        {cfg.icon}
                        <span className="text-[9px] font-bold uppercase tracking-widest">{node.type}</span>
                    </div>
                    <div className="text-xs font-bold text-white">{node.label}</div>
                    {node.audioFile && <div className="text-[9px] text-zinc-400 mt-0.5">{node.audioFile}</div>}
                </div>
                {node.children.length > 0 && (
                    <>
                        <div className="w-px h-6 bg-zinc-700" />
                        <div className="flex gap-8 relative">
                            {node.children.length > 1 && (
                                <div className="absolute top-0 left-0 right-0 h-px bg-zinc-700" style={{ marginLeft: "50%", marginRight: "50%", width: `calc(100% - ${100 / node.children.length}%)`, left: `${50 / node.children.length}%` }} />
                            )}
                            {node.children.map(childId => buildTree(childId, depth + 1))}
                        </div>
                    </>
                )}
            </div>
        );
    };

    return (
        <div className="min-h-screen bg-zinc-950 text-zinc-200 p-8 md:p-10">
            <div className="max-w-[1600px] mx-auto space-y-6">

                {/* Header */}
                <div className="bg-gradient-to-r from-amber-950/40 to-yellow-950/30 border border-amber-900/30 rounded-2xl p-6 flex items-center gap-5">
                    <div className="w-14 h-14 bg-amber-500/10 border border-amber-500/20 rounded-2xl flex items-center justify-center">
                        <GitBranch className="w-7 h-7 text-amber-400" />
                    </div>
                    <div className="flex-1">
                        <h1 className="text-xl font-bold text-white mb-1">DTMF IVR Builder</h1>
                        <p className="text-xs text-zinc-400">Visual IVR tree designer. Build DTMF menus, greetings, transfers, queues, and voicemail trees. Exports as Asterisk dialplan (extensions.conf).</p>
                    </div>
                    <div className="flex gap-3">
                        <button onClick={() => setShowDialplan(p => !p)} className="flex items-center gap-2 px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 rounded-xl text-xs font-bold transition-colors">
                            <Download className="w-3.5 h-3.5" /> {showDialplan ? "Hide" : "Export"} Dialplan
                        </button>
                        <button onClick={handleSave} className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition-all ${saved ? "bg-emerald-600 text-white" : "bg-amber-600 hover:bg-amber-500 text-white"}`}>
                            {saved ? <><CheckCircle2 className="w-3.5 h-3.5" /> Saved!</> : <><Save className="w-3.5 h-3.5" /> Save Dialplan</>}
                        </button>
                    </div>
                </div>

                <div className="grid lg:grid-cols-4 gap-6">
                    {/* Toolbox */}
                    <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-5 space-y-3">
                        <h2 className="text-xs font-bold text-zinc-400 uppercase tracking-widest mb-4">Add Node</h2>
                        {(Object.keys(NODE_COLORS) as NodeType[]).map(type => {
                            const cfg = NODE_COLORS[type];
                            return (
                                <button key={type} onClick={() => addNode(type)}
                                    className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl border transition-all hover:scale-105"
                                    style={{ background: cfg.bg, borderColor: cfg.border + "60" }}>
                                    <span style={{ color: cfg.border }}>{cfg.icon}</span>
                                    <span className="text-xs font-bold text-zinc-200 capitalize">{type}</span>
                                    <Plus className="w-3 h-3 text-zinc-500 ml-auto" />
                                </button>
                            );
                        })}

                        {selected && (
                            <div className="mt-6 space-y-3 border-t border-zinc-800 pt-4">
                                <h3 className="text-xs font-bold text-zinc-300">Edit: {selected.label}</h3>
                                <div>
                                    <label className="text-[10px] text-zinc-500 block mb-1">Label</label>
                                    <input value={selected.label} onChange={e => updateNode(selected.id, { label: e.target.value })}
                                        className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-2.5 py-1.5 text-xs text-zinc-200 focus:outline-none focus:border-amber-500" />
                                </div>
                                {selected.type === "menu" || selected.type === "transfer" ? (
                                    <div>
                                        <label className="text-[10px] text-zinc-500 block mb-1">DTMF Key</label>
                                        <input value={selected.dtmf || ""} onChange={e => updateNode(selected.id, { dtmf: e.target.value })}
                                            placeholder="1" className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-2.5 py-1.5 text-xs text-zinc-200 focus:outline-none focus:border-amber-500" />
                                    </div>
                                ) : null}
                                {selected.type === "transfer" || selected.type === "queue" ? (
                                    <div>
                                        <label className="text-[10px] text-zinc-500 block mb-1">Target (ext/queue)</label>
                                        <input value={selected.target || ""} onChange={e => updateNode(selected.id, { target: e.target.value })}
                                            placeholder="+61... or queue-name" className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-2.5 py-1.5 text-xs text-zinc-200 focus:outline-none focus:border-amber-500" />
                                    </div>
                                ) : null}
                                <div>
                                    <label className="text-[10px] text-zinc-500 block mb-1">Audio File</label>
                                    <input value={selected.audioFile || ""} onChange={e => updateNode(selected.id, { audioFile: e.target.value })}
                                        placeholder="greeting.mp3" className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-2.5 py-1.5 text-xs text-zinc-200 focus:outline-none focus:border-amber-500" />
                                </div>
                                {selected.id !== "start" && (
                                    <button onClick={() => deleteNode(selected.id)} className="w-full flex items-center justify-center gap-2 px-3 py-2 bg-red-500/10 border border-red-500/30 text-red-400 rounded-xl text-xs font-bold hover:bg-red-500/20 transition-colors">
                                        <Trash2 className="w-3.5 h-3.5" /> Delete Node
                                    </button>
                                )}
                            </div>
                        )}
                    </div>

                    {/* Canvas */}
                    <div className="col-span-3 space-y-4">
                        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-8 overflow-x-auto min-h-80">
                            <div className="flex justify-center">
                                {buildTree("start")}
                            </div>
                        </div>

                        {showDialplan && (
                            <div className="bg-zinc-900 border border-amber-900/30 rounded-2xl overflow-hidden">
                                <div className="flex items-center justify-between px-5 py-3 border-b border-zinc-800">
                                    <span className="text-xs font-bold text-zinc-300">Generated extensions.conf</span>
                                    <button onClick={() => navigator.clipboard.writeText(GENERATED_DIALPLAN)} className="text-[10px] text-zinc-400 hover:text-zinc-200 flex items-center gap-1">
                                        <ArrowRight className="w-3 h-3" /> Copy
                                    </button>
                                </div>
                                <pre className="p-5 text-[11px] font-mono text-emerald-300 overflow-x-auto">{GENERATED_DIALPLAN}</pre>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
